const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Mac Book Pro M4 PRO',
      slug: 'mac-book-pro-m4-pro',
      category: 'Computers',
      description: 'The best product to build your own project',
      images: ['/images/products/p1-1.jpg', '/images/products/p1-2.jpg'],
      price: 1599.99,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Apple Air Max',
      slug: 'apple-air-max',
      category: 'Accessories',
      description: 'Best sound in one headphone',
      images: ['/images/products/p2-1.jpg', '/images/products/p2-2.jpg'],
      price: 999.99,
      brand: 'Apple',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Mac Mini',
      slug: 'mac-mini',
      category: 'Computers',
      description: 'Small but powerfull',
      images: ['/images/products/p3-1.jpg', '/images/products/p3-2.jpg'],
      price: 599.99,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Mac Pro M2 Ultra',
      slug: 'mac-pro-m2-ultra',
      category: 'Computers',
      description: 'If you buy this you are idiot',
      images: ['/images/products/p4-1.jpg', '/images/products/p4-2.jpg'],
      price: 2599.95,
      brand: 'Apple',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'AirPods Pro 2 generation',
      slug: 'airpods-pro-2',
      category: 'Accessories',
      description: 'Excelent sound, buy it',
      images: ['/images/products/p5-1.jpg', '/images/products/p5-2.jpg'],
      price: 199.99,
      brand: 'Apple',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Magic keyBoard',
      slug: 'magic-keyboard',
      category: 'Accessories',
      description: 'Soft and Modern',
      images: ['/images/products/p6-1.jpg', '/images/products/p6-2.jpg'],
      price: 149.99,
      brand: 'Apple',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: '/images/banner-3.jpg',
    },
  ],
};

export default sampleData;
